apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  morrisons.server: |
    morrisons.site:53 {
        forward . {{ .Values.piholeAddress }}
    }
  {{- range $host, $ip := .Values.localHosts }}
  {{ $host }}.server: |
    {{ $host }}:53 {
        forward . {{ $.Values.piholeAddress }}
    }
  {{- end }}
